// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ7WN9oa2Zkw_0c-Ho_tP-wUcM4fyqvwo',
    appId: '1:1023421054374:web:92ce5d48a3aabefcc46367',
    messagingSenderId: '1023421054374',
    projectId: 'campus-connect-38daf',
    authDomain: 'campus-connect-38daf.firebaseapp.com',
    storageBucket: 'campus-connect-38daf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_W0koh2oLwIwta-lFuNoA8TmxMja54CA',
    appId: '1:1023421054374:android:295d5c0dbbf41acec46367',
    messagingSenderId: '1023421054374',
    projectId: 'campus-connect-38daf',
    storageBucket: 'campus-connect-38daf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE4jcNzO07cEfu0Uoe2xLBVDBPZe4VHFc',
    appId: '1:1023421054374:ios:66ddba8aa9c2a4d5c46367',
    messagingSenderId: '1023421054374',
    projectId: 'campus-connect-38daf',
    iosBundleId: 'com.brianabr.eventscalendar',
    storageBucket: 'campus-connect-38daf.firebasestorage.app',
  );
}
